### ISSUE TITLE
Crashes on Nexu 5 with Omnirom at every attempt to knock

### ISSUE THREAD

**Issue by languitar** [jp-bennett/Fwknop2#36]
The current fdroid version crashes everytime I try to knock a server. This is what logcat reports:

```
09-04 15:18:51.826  6692  6708 D AutoUpdateManager: network is not available, 0 in queue
09-04 15:18:53.373  8021  8047 V fwknop2 : Your external IP address is myip.opendns.com./80.187.111.118
09-04 15:18:53.373  8021  8047 V libfwknop: **** Init fwknop ****
09-04 15:18:53.373  8021  8047 V libfwknop: Detected key b64
09-04 15:18:53.383  8021  8047 E art     : JNI ERROR (app bug): attempt to use stale global reference 0x2 (should be 0x100002)
09-04 15:18:53.383  8021  8047 F art     : art/runtime/indirect_reference_table.cc:65] JNI ERROR (app bug): see above.
09-04 15:18:53.719  8021  8047 F art     : art/runtime/barrier.cc:90] Check failed: count_ == 0 (count_=-1, 0=0) Attempted to destroy barrier with non zero count
09-04 15:18:53.719  8021  8047 F art     : art/runtime/runtime.cc:366] Runtime aborting --- recursively, so no thread-specific detail!
09-04 15:18:53.719  8021  8047 F art     : art/runtime/runtime.cc:366] 
09-04 15:18:53.719  8021  8047 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 8047 (AsyncTask #5)
09-04 15:18:53.822  2463  2463 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-04 15:18:53.822  2463  2463 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30Y/3067468:user/release-keys'
09-04 15:18:53.822  2463  2463 F DEBUG   : Revision: '0'
09-04 15:18:53.822  2463  2463 F DEBUG   : ABI: 'arm'
09-04 15:18:53.822  2463  2463 F DEBUG   : pid: 8021, tid: 8047, name: AsyncTask #5  >>> org.cipherdyne.fwknop2 <<<
09-04 15:18:53.823  2463  2463 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-04 15:18:53.841  2463  2463 F DEBUG   : Abort message: 'art/runtime/indirect_reference_table.cc:65] JNI ERROR (app bug): see above.'
09-04 15:18:53.841  2463  2463 F DEBUG   :     r0 00000000  r1 00001f6f  r2 00000006  r3 9e2f7978
09-04 15:18:53.841  2463  2463 F DEBUG   :     r4 9e2f7980  r5 9e2f7930  r6 00000000  r7 0000010c
09-04 15:18:53.841  2463  2463 F DEBUG   :     r8 b4cbf800  r9 b4cbde44  sl b378bcdb  fp b4ca3468
09-04 15:18:53.841  2463  2463 F DEBUG   :     ip 00000006  sp 9e2f6fd0  lr b6d07bb9  pc b6d09fa8  cpsr 40070010
09-04 15:18:53.865  2463  2463 F DEBUG   : 
09-04 15:18:53.865  2463  2463 F DEBUG   : backtrace:
09-04 15:18:53.865  2463  2463 F DEBUG   :     #00 pc 00041fa8  /system/lib/libc.so (tgkill+12)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #01 pc 0003fbb5  /system/lib/libc.so (pthread_kill+32)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #02 pc 0001c31f  /system/lib/libc.so (raise+10)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #03 pc 000194d1  /system/lib/libc.so (__libc_android_abort+34)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #04 pc 000174bc  /system/lib/libc.so (abort+4)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #05 pc 00333981  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #06 pc 000f460b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #07 pc 000f08e1  /system/lib/libart.so (_ZN3art7BarrierD2Ev+216)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #08 pc 0035b483  /system/lib/libart.so (_ZN3art10ThreadList4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+162)
09-04 15:18:53.866  2463  2463 F DEBUG   :     #09 pc 00333a45  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+424)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #10 pc 000f460b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #11 pc 001de275  /system/lib/libart.so (_ZN3art22IndirectReferenceTable17AbortIfNoCheckJNIEv+64)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #12 pc 0025925b  /system/lib/libart.so (_ZN3art9JavaVMExt12DecodeGlobalEPNS_6ThreadEPv+506)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #13 pc 0035102b  /system/lib/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+174)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #14 pc 000e5779  /system/lib/libart.so (_ZN3art25JniMethodEndWithReferenceEP8_jobjectjPNS_6ThreadE+76)
09-04 15:18:53.867  2463  2463 F DEBUG   :     #15 pc 00764f6b  /data/app/org.cipherdyne.fwknop2-1/oat/arm/base.odex (offset 0x505000)
09-04 15:18:54.281  2463  2463 F DEBUG   : 
09-04 15:18:54.281  2463  2463 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_05
09-04 15:18:54.281  2463  2463 E DEBUG   : AM write failed: Broken pipe
09-04 15:18:54.282 12328 12544 I BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
09-04 15:18:54.285 12328  8099 W ActivityManager:   Force finishing activity org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity
09-04 15:18:54.335 12328 13393 W InputDispatcher: channel 'c5b9899 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-04 15:18:54.335 12328 13393 E InputDispatcher: channel 'c5b9899 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-04 15:18:54.335 12328 13393 W InputDispatcher: channel '7a34f37 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-04 15:18:54.335 12328 13393 E InputDispatcher: channel '7a34f37 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-04 15:18:54.351 12328 17801 I WindowState: WIN DEATH: Window{c5b9899 u0 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity}
09-04 15:18:54.351 12328 17801 W InputDispatcher: Attempted to unregister already unregistered input channel 'c5b9899 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)'
09-04 15:18:54.352 12328 14752 D GraphicsStats: Buffer count: 16
09-04 15:18:54.354 12328  9557 I WindowState: WIN DEATH: Window{7a34f37 u0 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity}
09-04 15:18:54.354 12328  9557 W InputDispatcher: Attempted to unregister already unregistered input channel '7a34f37 org.cipherdyne.fwknop2/biz.incomsystems.fwknop2.ConfigListActivity (server)'
09-04 15:18:54.390 11758 11758 I Zygote  : Process 8021 exited due to signal (6)
09-04 15:18:54.398 12328  8099 W ActivityManager: Exception thrown during pause
09-04 15:18:54.398 12328  8099 W ActivityManager: android.os.DeadObjectException
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:868)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2911)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2767)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12063)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11959)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12648)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12155)
09-04 15:18:54.398 12328  8099 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
09-04 15:18:54.401   182   182 E lowmemorykiller: Error opening /proc/8021/oom_score_adj; errno=2
09-04 15:18:54.426 12328  6831 I ActivityManager: Process org.cipherdyne.fwknop2 (pid 8021) has died
09-04 15:18:54.481 12328 14495 I OpenGLRenderer: Initialized EGL, version 1.4
09-04 15:18:54.484 12328 12343 I art     : Background partial concurrent mark sweep GC freed 38562(2MB) AllocSpace objects, 18(1432KB) LOS objects, 30% free, 36MB/52MB, paused 10.549ms total 159.385ms
09-04 15:18:54.548 23427  8102 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-04 15:18:54.585 23427  8102 D DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics or Lockbox.
09-04 15:18:54.857  6692  6708 D AutoUpdateManager: network is not available, 0 in queue
09-04 15:18:54.990 12328 12547 W WindowAnimator: Failed to dispatch window animation state change.
09-04 15:18:54.990 12328 12547 W WindowAnimator: android.os.DeadObjectException
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-04 15:18:54.990 12328 12547 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
09-04 15:18:54.991 12328 12547 W WindowAnimator: Failed to dispatch window animation state change.
09-04 15:18:54.991 12328 12547 W WindowAnimator: android.os.DeadObjectException
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-04 15:18:54.991 12328 12547 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by jp-bennett** [comment]
Hmm, very strange.  I'll see if I can figure out what's going on here.

**Comment by jp-bennett** [comment]
Can you test the newest released version, 1.2.3 to see if it's still an issue?

**Comment by languitar** [comment]
I will, once it is available as an fdroid update.

**Comment by languitar** [comment]
Still crashes with the new version

**Comment by jp-bennett** [comment]
What version of Omnirom are you using?  Is this Marshmallow, Lollipop, etc?  To replicate and fix, I'll almost certainly have to load omnirom on a phone.  Unfortunately the crash log doesn't have much helpful info.  I'll keep after it.

**Comment by jp-bennett** [comment]
Alternatively, have you grabbed the latest omnirom release for your device?

**Comment by languitar** [comment]
It is a self-compiled omnirom 6.0.1-20160809
